FROM python:3.9

WORKDIR /backend

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .
# EXPOSE 8080

# RUN apk add --no-cache gcc python3-dev musl-dev

# ADD . /django_ec2

# WORKDIR /django_ec2

# RUN pip install -r requirements.txt

# RUN python django_ec2_project/manage.py makemigrations

# RUN python django_ec2_project/manage.py migrate

# CMD ["python","django_ec2_project/manage.py","runserver","0.0.0.0:8000" ]