# Generated by Django 3.2.8 on 2021-10-31 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20211028_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('cart_id', models.AutoField(max_length=128, primary_key=True, serialize=False, verbose_name='cart id')),
                ('quantity', models.IntegerField(default=1, verbose_name='product quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.specificationoption', verbose_name='spec_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'cart',
                'db_table': 'df_cart',
            },
        ),
    ]
