# Generated by Django 3.2.8 on 2021-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20211101_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(max_length=50, null=True, verbose_name='size'),
        ),
    ]
