# Generated by Django 3.2.8 on 2021-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211113_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='review_image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='review_text'),
        ),
    ]
