# Generated by Django 3.2.8 on 2021-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211113_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], max_length=5, null=True, verbose_name='Satisfaction Degree'),
        ),
    ]
