# Generated by Django 3.2.8 on 2021-10-31 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20211028_0727'),
        ('user', '0007_auto_20211015_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='order id')),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'Cash on delivery'), (2, 'We Chat'), (3, 'Alipay'), (4, 'Visa Card')], default=1, verbose_name='pya method')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='total price')),
                ('order_status', models.SmallIntegerField(choices=[(1, 'Order Placed'), (2, 'Preparing to Ship'), (3, 'Shipped'), (4, 'Delivered'), (5, 'Complete')], default=1, verbose_name='order status')),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address', verbose_name='address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'df_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('quantity', models.IntegerField(default=1, verbose_name='product quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderinfo', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order products',
                'verbose_name_plural': 'order products',
                'db_table': 'df_order_products',
            },
        ),
    ]
