# Generated by Django 3.2.8 on 2021-11-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='color',
            field=models.CharField(default='white', max_length=50, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='size',
            field=models.CharField(default='M', max_length=5, verbose_name='size'),
        ),
    ]
