# Generated by Django 3.2.8 on 2021-11-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211101_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='product_description'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='desc_image',
            field=models.TextField(blank=True, null=True, verbose_name='desc_image'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='default_image'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='product_name'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='tag'),
        ),
    ]
