# Generated by Django 3.2.8 on 2021-11-09 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('m_id', models.AutoField(primary_key=True, serialize=False, verbose_name='cart id')),
                ('is_from_user', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='from_user')),
                ('is_read', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='is_read')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'message',
                'db_table': 'df_message',
            },
        ),
    ]
