# Generated by Django 3.2.8 on 2021-11-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='img'),
        ),
    ]
