# Generated by Django 3.2.8 on 2021-10-15 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211007_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addr',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('Australia', 'Australia')], max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia'), ('ACT', 'Australian Capital Territory'), ('JBT', 'Jervis Bay Territory'), ('NT', 'Northern Territory')], max_length=50, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_addr',
            field=models.CharField(max_length=256, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
