# Generated by Django 3.2.8 on 2021-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('userID', models.BigIntegerField(null=True, verbose_name='user-id')),
                ('productID', models.BigIntegerField(null=True, verbose_name='product-id')),
                ('category1', models.BigIntegerField(null=True, verbose_name='category1-id')),
                ('category2', models.BigIntegerField(null=True, verbose_name='category2-id')),
                ('category3', models.BigIntegerField(null=True, verbose_name='category3-id')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='brand')),
                ('behaviour', models.SmallIntegerField(blank=True, choices=[(1, 'view product page'), (2, 'add to wishlist'), (3, 'add to cart'), (4, 'place an order'), (5, 'review rating'), (0, 'default')], default=0, null=True, verbose_name='user-behaviour')),
            ],
            options={
                'verbose_name': 'user-behaviour',
                'verbose_name_plural': 'user-behaviour',
                'db_table': 'df_user-behaviour',
            },
        ),
    ]
