# Generated by Django 3.2.8 on 2021-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userbehavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavour',
            name='star',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=5, null=True, verbose_name='Satisfaction Degree'),
        ),
    ]
