# Generated by Django 3.2.8 on 2021-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userbehavour_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='State/Province'),
        ),
    ]
