# Generated by Django 3.2.8 on 2021-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('sales', models.IntegerField(default=0, verbose_name='Quantity sold')),
                ('validdt', models.DateTimeField(verbose_name='product valid date and time')),
                ('inventory', models.IntegerField(default=0, verbose_name='product inventory')),
                ('validity', models.SmallIntegerField(choices=[(0, 'on shelves'), (1, 'off shelves')], default=0, verbose_name='product validity')),
                ('desc', models.CharField(max_length=1024, verbose_name='product description')),
                ('brand', models.CharField(max_length=50, verbose_name='brand')),
                ('size', models.CharField(max_length=10, verbose_name='size')),
                ('imgurl', models.URLField(verbose_name='images url')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'df_products',
            },
        ),
    ]
