# Generated by Django 3.2.8 on 2021-10-11 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='validdt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='product valid date and time'),
        ),
    ]
