# Generated by Django 3.2.8 on 2021-10-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_validdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='validdt',
            field=models.DateTimeField(verbose_name='product valid date and time'),
        ),
    ]
