# Generated by Django 3.2.8 on 2021-10-28 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211028_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat1_spu', to='products.productcategory', verbose_name='primary_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat2_spu', to='products.productcategory', verbose_name='second_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat3_spu', to='products.productcategory', verbose_name='third_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_image',
            field=models.TextField(blank=True, null=True, verbose_name='desc_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='default_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='product_inventory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='product_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity_sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='validdt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='product_valid_date_and_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='validity',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'on shelves'), (1, 'off shelves')], default=0, null=True, verbose_name='product_validity'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='inventory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='spec_prod_inventory'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='prod_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product', verbose_name='specification'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='size'),
        ),
    ]
