# Generated by Django 3.2.8 on 2021-11-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211028_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationoption',
            old_name='prod_id',
            new_name='prod',
        ),
    ]
