# Generated by Django 3.2.8 on 2021-11-17 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_rename_prod_id_specificationoption_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='his_product_name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='his_product_price')),
                ('image', models.TextField(blank=True, null=True, verbose_name='his_default_image')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='hist_prod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='hist_user')),
            ],
            options={
                'verbose_name': 'browse_history',
                'verbose_name_plural': 'browse_history',
                'db_table': 'df_browse_history',
            },
        ),
    ]
